In [35]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (2.3.1)

In [36]:
import numpy as np

In [37]:
array = [0,1,2,3,4,5,6,7,8,9,10]

In [38]:
array[3:8]

[3, 4, 5, 6, 7]

In [39]:
a = 10
b = 3.14

In [40]:
type(b)

float

In [41]:
type(a+b)

float

In [42]:
items = [10, 20, 30, 40, 50, 60]

In [43]:
for items in item :
    print(items)

NameError: name 'item' is not defined

In [ ]:
func2 = lambda a,b : print(a+b)

In [ ]:
func2(5,4)

9

In [ ]:
items

[10, 20, 30, 40, 50, 60]

In [ ]:
[item**2 for item in items]

[100, 400, 900, 1600, 2500, 3600]

In [ ]:
pip i pandas

Note: you may need to restart the kernel to use updated packages.

ERROR: unknown command "i"

In [ ]:
pip install pandas

Collecting pandas
  Downloading pandas-2.3.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.1-cp313-cp313-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 519.0 kB/s eta 0:00:21
   - -------------------------------------- 0.5/11.0 MB 519.0 kB/s eta 0:00:21
   -- ------------------------------------- 0.8/11.0 MB 598.2 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/11.0 MB 678.2 kB/s eta 0:00:15
   --- ------------------------------------ 1.0/11.0 MB 678.2 kB/s eta 0:00:15
   ---- ----------------------------------- 1.3/11.0 MB 660.5 kB/s eta 0:00:15
   ---- ----------------------------------- 1.3/11.0 MB 660.5 kB/s eta 0:00:15
   ----- ---------------------------------- 1.6/11.0 MB 680.9 kB/s eta 0:00:14
   ------ --------------------------------- 1.8/11.0 MB 737.1 kB/s eta 0:00:13
   ------ --------------------------------- 1.8/11.0 MB 737.1 kB/s eta 0:00:13
   ------ --------------------------------- 1.8/11.0 MB 737.1 kB/s eta 0:00:13
   ------ --------------------------------- 1.8/11.0 MB 737.1 kB/s eta 0:00:13
   ------- -------------------------------- 2.1/11.0 MB 615.3 kB/s eta 0:00:15
   -------- ------------------------------- 2.4/11.0 MB 648.0 kB/s eta 0:00:14
   --------- ------------------------------ 2.6/11.0 MB 676.9 kB/s eta 0:00:13
   ---------- ----------------------------- 2.9/11.0 MB 707.9 kB/s eta 0:00:12
   ----------- ---------------------------- 3.1/11.0 MB 748.6 kB/s eta 0:00:11
   ------------ --------------------------- 3.4/11.0 MB 779.9 kB/s eta 0:00:10
   ------------ --------------------------- 3.4/11.0 MB 779.9 kB/s eta 0:00:10
   ------------- -------------------------- 3.7/11.0 MB 765.0 kB/s eta 0:00:10
   -------------- ------------------------- 3.9/11.0 MB 769.9 kB/s eta 0:00:10
   -------------- ------------------------- 3.9/11.0 MB 769.9 kB/s eta 0:00:10
   -------------- ------------------------- 3.9/11.0 MB 769.9 kB/s eta 0:00:10
   --------------- ------------------------ 4.2/11.0 MB 747.3 kB/s eta 0:00:10
   --------------- ------------------------ 4.2/11.0 MB 747.3 kB/s eta 0:00:10
   ---------------- ----------------------- 4.5/11.0 MB 748.1 kB/s eta 0:00:09
   ----------------- ---------------------- 4.7/11.0 MB 763.2 kB/s eta 0:00:09
   ------------------ --------------------- 5.0/11.0 MB 773.4 kB/s eta 0:00:08
   ------------------- -------------------- 5.2/11.0 MB 794.4 kB/s eta 0:00:08
   -------------------- ------------------- 5.8/11.0 MB 831.3 kB/s eta 0:00:07
   --------------------- ------------------ 6.0/11.0 MB 858.0 kB/s eta 0:00:06
   ---------------------- ----------------- 6.3/11.0 MB 871.5 kB/s eta 0:00:06
   ----------------------- ---------------- 6.6/11.0 MB 870.4 kB/s eta 0:00:06
   ------------------------ --------------- 6.8/11.0 MB 884.7 kB/s eta 0:00:05
   ------------------------- -------------- 7.1/11.0 MB 901.6 kB/s eta 0:00:05
   --------------------------- ------------ 7.6/11.0 MB 939.2 kB/s eta 0:00:04
   ---------------------------- ----------- 7.9/11.0 MB 951.1 kB/s eta 0:00:04
   ----------------------------- ---------- 8.1/11.0 MB 969.8 kB/s eta 0:00:03
   ------------------------------ --------- 8.4/11.0 MB 968.9 kB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 967.0 kB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 967.0 kB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 967.0 kB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 930.6 kB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 930.6 kB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 930.6 kB/s eta 0:00:03
   --------------------------------- ------ 9.2/11.0 MB 913.6 kB/s eta 0:00:02
   ---------------------------------- ----- 9.4/11.0 MB 923.5 kB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 923.1 kB/s eta 0:00:02
   ------------------------------------ --- 10.0/11.0 MB 926.0 kB/s eta 0:00:02
   ------------------------------------ --- 10.0/11.0 MB 926.0 kB/s eta 0:00:02
   ------------------------------------- -- 10.2/11.0 MB 923.1 kB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 927.3 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 930.4 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 930.4 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 930.4 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 930.4 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 930.4 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 930.4 kB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 857.7 kB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas

   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed pandas-2.3.1 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from seaborn) (2.3.1)
Requirement already satisfied: pandas>=1.2 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from seaborn) (2.3.1)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.10.3-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.3.2-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.58.5-cp313-cp313-win_amd64.whl.metadata (109 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.4.8-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pillow-11.3.0-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Collecting pyparsing>=2.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kada-04\anaconda3\envs\python3.13\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.3-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 1.1 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/8.1 MB 1.1 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/8.1 MB 757.6 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 757.6 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 757.6 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 757.6 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 757.6 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 757.6 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 757.6 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 757.6 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 757.6 kB/s eta 0:00:10
   ----- ---------------------------------- 1.0/8.1 MB 303.9 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.1 MB 303.9 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.1 MB 303.9 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.1 MB 303.9 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.1 MB 303.9 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.1 MB 303.9 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.1 MB 303.9 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.1 MB 303.9 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.1 MB 303.9 kB/s eta 0:00:24
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------ --------------------------------- 1.3/8.1 MB 243.7 kB/s eta 0:00:28
   ------- -------------------------------- 1.6/8.1 MB 175.9 kB/s eta 0:00:37
   ------- -------------------------------- 1.6/8.1 MB 175.9 kB/s eta 0:00:37
   ------- -------------------------------- 1.6/8.1 MB 175.9 kB/s eta 0:00:37
   ------- -------------------------------- 1.6/8.1 MB 175.9 kB/s eta 0:00:37
   ------- -------------------------------- 1.6/8.1 MB 175.9 kB/s eta 0:00:37
   --------- ------------------------------ 1.8/8.1 MB 187.6 kB/s eta 0:00:34
   --------- ------------------------------ 1.8/8.1 MB 187.6 kB/s eta 0:00:34
   --------- ------------------------------ 1.8/8.1 MB 187.6 kB/s eta 0:00:34
   ---------- ----------------------------- 2.1/8.1 MB 201.3 kB/s eta 0:00:30
   ---------- ----------------------------- 2.1/8.1 MB 201.3 kB/s eta 0:00:30
   ---------- ----------------------------- 2.1/8.1 MB 201.3 kB/s eta 0:00:30
   ---------- ----------------------------- 2.1/8.1 MB 201.3 kB/s eta 0:00:30
   ---------- ----------------------------- 2.1/8.1 MB 201.3 kB/s eta 0:00:30
   ---------- ----------------------------- 2.1/8.1 MB 201.3 kB/s eta 0:00:30
   ---------- ----------------------------- 2.1/8.1 MB 201.3 kB/s eta 0:00:30
   ----------- ---------------------------- 2.4/8.1 MB 200.4 kB/s eta 0:00:29
   ----------- ---------------------------- 2.4/8.1 MB 200.4 kB/s eta 0:00:29
   ------------ --------------------------- 2.6/8.1 MB 214.1 kB/s eta 0:00:26
   ------------ --------------------------- 2.6/8.1 MB 214.1 kB/s eta 0:00:26
   ------------ --------------------------- 2.6/8.1 MB 214.1 kB/s eta 0:00:26
   ------------ --------------------------- 2.6/8.1 MB 214.1 kB/s eta 0:00:26
   ------------ --------------------------- 2.6/8.1 MB 214.1 kB/s eta 0:00:26
   ------------ --------------------------- 2.6/8.1 MB 214.1 kB/s eta 0:00:26
   ------------ --------------------------- 2.6/8.1 MB 214.1 kB/s eta 0:00:26
   ------------ --------------------------- 2.6/8.1 MB 214.1 kB/s eta 0:00:26
   -------------- ------------------------- 2.9/8.1 MB 208.0 kB/s eta 0:00:25
   -------------- ------------------------- 2.9/8.1 MB 208.0 kB/s eta 0:00:25
   -------------- ------------------------- 2.9/8.1 MB 208.0 kB/s eta 0:00:25
   -------------- ------------------------- 2.9/8.1 MB 208.0 kB/s eta 0:00:25
   -------------- ------------------------- 2.9/8.1 MB 208.0 kB/s eta 0:00:25
   -------------- ------------------------- 2.9/8.1 MB 208.0 kB/s eta 0:00:25
   --------------- ------------------------ 3.1/8.1 MB 205.5 kB/s eta 0:00:24
   --------------- ------------------------ 3.1/8.1 MB 205.5 kB/s eta 0:00:24
   --------------- ------------------------ 3.1/8.1 MB 205.5 kB/s eta 0:00:24
   --------------- ------------------------ 3.1/8.1 MB 205.5 kB/s eta 0:00:24
   --------------- ------------------------ 3.1/8.1 MB 205.5 kB/s eta 0:00:24
   --------------- ------------------------ 3.1/8.1 MB 205.5 kB/s eta 0:00:24
   ---------------- ----------------------- 3.4/8.1 MB 205.1 kB/s eta 0:00:23
   ---------------- ----------------------- 3.4/8.1 MB 205.1 kB/s eta 0:00:23
   ---------------- ----------------------- 3.4/8.1 MB 205.1 kB/s eta 0:00:23
   ---------------- ----------------------- 3.4/8.1 MB 205.1 kB/s eta 0:00:23
   ---------------- ----------------------- 3.4/8.1 MB 205.1 kB/s eta 0:00:23
   ---------------- ----------------------- 3.4/8.1 MB 205.1 kB/s eta 0:00:23
   ---------------- ----------------------- 3.4/8.1 MB 205.1 kB/s eta 0:00:23
   ------------------ --------------------- 3.7/8.1 MB 204.2 kB/s eta 0:00:22
   ------------------ --------------------- 3.7/8.1 MB 204.2 kB/s eta 0:00:22
   ------------------ --------------------- 3.7/8.1 MB 204.2 kB/s eta 0:00:22
   ------------------- -------------------- 3.9/8.1 MB 210.8 kB/s eta 0:00:20
   ------------------- -------------------- 3.9/8.1 MB 210.8 kB/s eta 0:00:20
   ------------------- -------------------- 3.9/8.1 MB 210.8 kB/s eta 0:00:20
   ------------------- -------------------- 3.9/8.1 MB 210.8 kB/s eta 0:00:20
   ------------------- -------------------- 3.9/8.1 MB 210.8 kB/s eta 0:00:20
   ------------------- -------------------- 3.9/8.1 MB 210.8 kB/s eta 0:00:20
   -------------------- ------------------- 4.2/8.1 MB 210.9 kB/s eta 0:00:19
   -------------------- ------------------- 4.2/8.1 MB 210.9 kB/s eta 0:00:19
   -------------------- ------------------- 4.2/8.1 MB 210.9 kB/s eta 0:00:19
   -------------------- ------------------- 4.2/8.1 MB 210.9 kB/s eta 0:00:19
   -------------------- ------------------- 4.2/8.1 MB 210.9 kB/s eta 0:00:19
   -------------------- ------------------- 4.2/8.1 MB 210.9 kB/s eta 0:00:19
   -------------------- ------------------- 4.2/8.1 MB 210.9 kB/s eta 0:00:19
   -------------------- ------------------- 4.2/8.1 MB 210.9 kB/s eta 0:00:19
   ---------------------- ----------------- 4.5/8.1 MB 206.7 kB/s eta 0:00:18
   ---------------------- ----------------- 4.5/8.1 MB 206.7 kB/s eta 0:00:18
   ---------------------- ----------------- 4.5/8.1 MB 206.7 kB/s eta 0:00:18
   ---------------------- ----------------- 4.5/8.1 MB 206.7 kB/s eta 0:00:18
   ----------------------- ---------------- 4.7/8.1 MB 212.4 kB/s eta 0:00:16
   ----------------------- ---------------- 4.7/8.1 MB 212.4 kB/s eta 0:00:16
   ----------------------- ---------------- 4.7/8.1 MB 212.4 kB/s eta 0:00:16
   ----------------------- ---------------- 4.7/8.1 MB 212.4 kB/s eta 0:00:16
   ----------------------- ---------------- 4.7/8.1 MB 212.4 kB/s eta 0:00:16
   ----------------------- ---------------- 4.7/8.1 MB 212.4 kB/s eta 0:00:16
   ------------------------ --------------- 5.0/8.1 MB 211.5 kB/s eta 0:00:15
   ------------------------ --------------- 5.0/8.1 MB 211.5 kB/s eta 0:00:15
   ------------------------ --------------- 5.0/8.1 MB 211.5 kB/s eta 0:00:15
   ------------------------ --------------- 5.0/8.1 MB 211.5 kB/s eta 0:00:15
   ------------------------ --------------- 5.0/8.1 MB 211.5 kB/s eta 0:00:15
   ------------------------ --------------- 5.0/8.1 MB 211.5 kB/s eta 0:00:15
   ------------------------ --------------- 5.0/8.1 MB 211.5 kB/s eta 0:00:15
   ------------------------ --------------- 5.0/8.1 MB 211.5 kB/s eta 0:00:15
   ------------------------ --------------- 5.0/8.1 MB 211.5 kB/s eta 0:00:15
   ------------------------- -------------- 5.2/8.1 MB 205.0 kB/s eta 0:00:14
   ------------------------- -------------- 5.2/8.1 MB 205.0 kB/s eta 0:00:14
   ------------------------- -------------- 5.2/8.1 MB 205.0 kB/s eta 0:00:14
   ------------------------- -------------- 5.2/8.1 MB 205.0 kB/s eta 0:00:14
   ------------------------- -------------- 5.2/8.1 MB 205.0 kB/s eta 0:00:14
   ------------------------- -------------- 5.2/8.1 MB 205.0 kB/s eta 0:00:14
   ------------------------- -------------- 5.2/8.1 MB 205.0 kB/s eta 0:00:14
   ------------------------- -------------- 5.2/8.1 MB 205.0 kB/s eta 0:00:14
   ------------------------- -------------- 5.2/8.1 MB 205.0 kB/s eta 0:00:14
   --------------------------- ------------ 5.5/8.1 MB 201.4 kB/s eta 0:00:13
   --------------------------- ------------ 5.5/8.1 MB 201.4 kB/s eta 0:00:13
   --------------------------- ------------ 5.5/8.1 MB 201.4 kB/s eta 0:00:13
   --------------------------- ------------ 5.5/8.1 MB 201.4 kB/s eta 0:00:13
   --------------------------- ------------ 5.5/8.1 MB 201.4 kB/s eta 0:00:13
   --------------------------- ------------ 5.5/8.1 MB 201.4 kB/s eta 0:00:13
   ---------------------------- ----------- 5.8/8.1 MB 201.3 kB/s eta 0:00:12
   ---------------------------- ----------- 5.8/8.1 MB 201.3 kB/s eta 0:00:12
   ----------------------------- ---------- 6.0/8.1 MB 207.1 kB/s eta 0:00:10
   ----------------------------- ---------- 6.0/8.1 MB 207.1 kB/s eta 0:00:10
   ----------------------------- ---------- 6.0/8.1 MB 207.1 kB/s eta 0:00:10
   ----------------------------- ---------- 6.0/8.1 MB 207.1 kB/s eta 0:00:10
   ----------------------------- ---------- 6.0/8.1 MB 207.1 kB/s eta 0:00:10
   ----------------------------- ---------- 6.0/8.1 MB 207.1 kB/s eta 0:00:10
   ----------------------------- ---------- 6.0/8.1 MB 207.1 kB/s eta 0:00:10
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.1 MB 206.1 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   -------------------------------- ------- 6.6/8.1 MB 185.0 kB/s eta 0:00:09
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   --------------------------------- ------ 6.8/8.1 MB 169.7 kB/s eta 0:00:08
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ----------------------------------- ---- 7.1/8.1 MB 142.8 kB/s eta 0:00:07
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06
   ------------------------------------ --- 7.3/8.1 MB 134.3 kB/s eta 0:00:06

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
sns.load_dataset("iris")

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df = sns.load_dataset("iris")

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df[10:]

     sepal_length  sepal_width  petal_length  petal_width    species
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[140 rows x 5 columns]

In [ ]:
df[["sepal_length", "petal_length"]]

     sepal_length  petal_length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

In [ ]:
df[df["species"] == "setosa" ]

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [ ]:
df["petal_width"][2:5]

2    0.2
3    0.2
4    0.2
Name: petal_width, dtype: float64

In [ ]:
df["petal_width"].value_counts()

petal_width
0.2    29
1.3    13
1.5    12
1.8    12
1.4     8
2.3     8
0.4     7
1.0     7
0.3     7
2.1     6
2.0     6
1.2     5
0.1     5
1.9     5
1.6     4
2.5     3
2.2     3
1.1     3
2.4     3
1.7     2
0.6     1
0.5     1
Name: count, dtype: int64

In [ ]:
df["sepal_length"].astype(int)

0      5
1      4
2      4
3      4
4      5
      ..
145    6
146    6
147    6
148    6
149    5
Name: sepal_length, Length: 150, dtype: int64

In [ ]:
df = sns.load_dataset("titanic")

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df["petal_width"]*10

0       2.0
1       2.0
2       2.0
3       2.0
4       2.0
       ...
145    23.0
146    19.0
147    20.0
148    23.0
149    18.0
Name: petal_width, Length: 150, dtype: float64

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df["sepal_length"].mean()

np.float64(5.843333333333334)

In [ ]:
df.groupby("species")["petal_length"].describe()

            count   mean       std  min  25%   50%    75%  max
species
setosa       50.0  1.462  0.173664  1.0  1.4  1.50  1.575  1.9
versicolor   50.0  4.260  0.469911  3.0  4.0  4.35  4.600  5.1
virginica    50.0  5.552  0.551895  4.5  5.1  5.55  5.875  6.9

In [ ]:
df[df["sepal_length"] >5 ]

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[118 rows x 5 columns]

In [ ]:
df.loc[0:10, ["sepal_length", "species"]]

    sepal_length species
0            5.1  setosa
1            4.9  setosa
2            4.7  setosa
3            4.6  setosa
4            5.0  setosa
5            5.4  setosa
6            4.6  setosa
7            5.0  setosa
8            4.4  setosa
9            4.9  setosa
10           5.4  setosa

In [ ]:
df.loc[df["sepal_length"] > 5, ["sepal_length", "species"]]

     sepal_length    species
0             5.1     setosa
5             5.4     setosa
10            5.4     setosa
14            5.8     setosa
15            5.7     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[118 rows x 2 columns]

In [ ]:
df.iloc[1:5, 1:5]

   sepal_width  petal_length  petal_width species
1          3.0           1.4          0.2  setosa
2          3.2           1.3          0.2  setosa
3          3.1           1.5          0.2  setosa
4          3.6           1.4          0.2  setosa
5          3.9           1.7          0.4  setosa
6          3.4           1.4          0.3  setosa
7          3.4           1.5          0.2  setosa
8          2.9           1.4          0.2  setosa
9          3.1           1.5          0.1  setosa

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df.iloc[3:5, 0:3]

   sepal_length  sepal_width  petal_length
3           4.6          3.1           1.5
4           5.0          3.6           1.4

In [ ]:
df.sort_values("sepal_length", ascending=False).reset_index()

     index  sepal_length  sepal_width  petal_length  petal_width    species
0      131           7.9          3.8           6.4          2.0  virginica
1      122           7.7          2.8           6.7          2.0  virginica
2      118           7.7          2.6           6.9          2.3  virginica
3      117           7.7          3.8           6.7          2.2  virginica
4      135           7.7          3.0           6.1          2.3  virginica
..     ...           ...          ...           ...          ...        ...
145     41           4.5          2.3           1.3          0.3     setosa
146     42           4.4          3.2           1.3          0.2     setosa
147      8           4.4          2.9           1.4          0.2     setosa
148     38           4.4          3.0           1.3          0.2     setosa
149     13           4.3          3.0           1.1          0.1     setosa

[150 rows x 6 columns]

In [ ]:
df.sort_values("sepal_length", ascending=False).reset_index().drop(0, axis=0).rename(columns={"index" : "previous_index"})

,previous_index,sepal_length,sepal_width,petal_length,petal_width,species
1,122,7.7,2.8,6.7,2.0,virginica
2,118,7.7,2.6,6.9,2.3,virginica
3,117,7.7,3.8,6.7,2.2,virginica
4,135,7.7,3.0,6.1,2.3,virginica
5,105,7.6,3.0,6.6,2.1,virginica
...,...,...,...,...,...,...
145,41,4.5,2.3,1.3,0.3,setosa
146,42,4.4,3.2,1.3,0.2,setosa
147,8,4.4,2.9,1.4,0.2,setosa
148,38,4.4,3.0,1.3,0.2,setosa
149,13,4.3,3.0,1.1,0.1,setosa

In [ ]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
titanic = sns.load_dataset("titanic")

In [ ]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df = sns.load_dataset("tips")

In [ ]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
grouped = df.groupby('day', observed=False).agg(total_customers=('smoker', 'count'),smoker_count=('smoker', lambda x: (x == 'Yes').sum()))

In [ ]:
grouped['smoker_proportion'] = grouped['smoker_count'] / grouped['total_customers']

In [ ]:
sorted_days = grouped.sort_values('smoker_proportion', ascending=False)

In [ ]:
result = sorted_days[['smoker_proportion']]
print(result)

      smoker_proportion
day
Fri            0.789474
Sat            0.482759
Thur           0.274194
Sun            0.250000

In [ ]:
df = sns.load_dataset("titanic")

NameError: name 'sns' is not defined

In [ ]:
df

NameError: name 'df' is not defined

In [ ]:
features = ["pclass", "sex", "age", "embark_town", "alive", "alone"]

In [ ]:
df.groupby(features)["age"].mean()

pclass  sex     age   embark_town  alive  alone
1       female  2.0   Southampton  no     False     2.0
                14.0  Southampton  yes    False    14.0
                15.0  Southampton  yes    False    15.0
                16.0  Cherbourg    yes    False    16.0
                      Southampton  yes    False    16.0
                                                   ...
3       male    59.0  Southampton  no     True     59.0
                61.0  Southampton  no     True     61.0
                65.0  Queenstown   no     True     65.0
                70.5  Queenstown   no     True     70.5
                74.0  Southampton  no     True     74.0
Name: age, Length: 497, dtype: float64

In [44]:
df

NameError: name 'df' is not defined